language: java
jdk:
- oraclejdk8
- oraclejdk9
env:
  matrix:
  - COVERAGE=0.05 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.14 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.36 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.12 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.31 BUILD_TARGET=./monolithic/repository/user
  global:
  - DOCKER_LOGIN=wenlock
  - secure: SB0pJJmfl4jX1h7c9uvEzGIw2RVRFynb2do27CWOEMvHeCPEINbApiFHuDqrvH/AQkvPrgCEma3auJLBbVHFtQEvoBlBe6hZFjtKvtU8+gYFyQ44hpPWq0wXwlX0Hs7HvBHL8oaFLKl/pufwyFumIjLzYQbtdzivSqwCDodL36LUpS9bRlmfcbIV0OsUvqxnhDNH5nqWspQnRcmdqLaRYtpUu5U+xp6nF6LwxRxCt+jlcMRUc3fCc/C/utgDdG20f65ERFjtRBZ7gJEbTmZyb1zyoXnEyYVfu5AK+NL2v3h7DkeISlafJqLuFA1FVM+r9N/XDZvf693zvAYOBq2YbO0R5nUGM7qOmgiBXXoiDdW+u3lDhPyltjNU5w0Hmq1/V3VXniDonQEhgZR+68iRR7FQ/dtNok2QRhAJRD1pg27Ea8jzZXUo5EvJg+H2zRgTWU2FfQHTPbljWxt0RflEuew7seYSFKniK53EW6B8kZYs97BxzeGQxndCWfqeQFNCmxRVZw0hMaH/UttuQC/HnLt3wW2BBWR97sdUHuIoboAugoZCv9wUK5HhdAzpYKL8chv3hPBKmwtKKP5x2oqFV8LHDn89uVH2jxtIwpMpDG7CYrKdlr/NdNtwQ17LEXpMXnSdiQeDqVJFpe3gDZEIkafLgUbf7IfXnIgwpbba0HQ=
install:
- "./gradlew clean jar"
script:
- "./gradlew -p $BUILD_TARGET check"
after_success:
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
- echo "Build succedded for $BUILD_TARGET"
before_deploy:
- "./gradlew -p ./monolithic/ui packageToContainer ;"
- echo "Build target is -> $BUILD_TARGET"
deploy:
  provider: script
  script: bash -c "echo \"running for $BUILD_TARGET\" \ && docker login --password
    \"${DOCKER_PASSWORD}\" --username \"${DOCKER_LOGIN}\" \ && docker tag zutherb/monolithic-shop:latest
    ${DOCKER_LOGIN}/monolithic-shop:latest \ && docker push $DOCKER_LOGIN/monolithic-shop:latest"
  on:
    all_branches: true
