language: java
jdk:
- oraclejdk8
- oraclejdk9
env:
  matrix:
  - COVERAGE=0.05 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.14 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.36 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.12 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.31 BUILD_TARGET=./monolithic/repository/user
  global:
  - DOCKER_LOGIN=wenlock
  - secure: keg2l1qpjw+JAM7KPsg5Iqo3zjgAtmILtwoXq2i91eg3wSDCbdq3Q6lqBojWmB4QXHfyrHO8lX+v718H+uuqrS3xA3Kpysz/+jJShh1PPjZYe2LosQzEtRlMbwW8Hf/CffJ9IqalCRf6wT3BJArEWnHyg4Xqbcoh6yteKjaeQRlFVSNXL2cM94t52vnGfHFoiHgzOwwSV/4efHZEh2cgB7XXzLD9ifXndU1Gi7u+5OQ6qB0UB/ZXs5eUhuYBowVBNMTCny9z4HSnihcgVaL08ixK60BtBcfYp320kfTSDAIb7cvDMdLI/P7ZFZfGTsVF2HH7Km8JGHqxIZnT6J9AspMsvZICUjRiE/5k2Q+gE87bNKp2Mxk5dis6quK7LDDSTM+uxoMBfOJqfZ4idVi2PMNDfP3sE0XAS21/WoSYP/+k8xIhdAqySmwjZziAt5pPbwhaDHpxpE1oBM8G1DBEfzAnqtMUdG7ukwC+FrNv0tQMYprz0m9aTAHF+ix3oOg2rfvuYLcr65Wg2+yQbB4V8C/pMJB+mmphztLrQU0J0d7xLanX7N3k7T1qQINhWB2tH3OFmPqKZwWOIA5nErLgGGPFVHePFEFsSa6nhh8inQJgdngecrnRCy3/5ty4JDHW8PlCTZN2oqCwHha8nhnfu4QyZXhup/QOlSaFpAq3iPA=
install:
- "./gradlew clean jar"
script:
- "./gradlew -p $BUILD_TARGET check"
after_success:
- find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
- echo "Build succedded for $BUILD_TARGET"
before_deploy:
- "./gradlew -p ./monolithic/ui packageToContainer ;"
- echo "Build target is --> $BUILD_TARGET"
deploy:
  provider: script
  script: >
      bash -c "echo \"${DOCKER_PASSWORD}\" | \
         docker login --username \"${DOCKER_LOGIN}\" --password-stdin \
      && docker tag zutherb/monolithic-shop:latest $DOCKER_LOGIN/monolithic-shop:latest \
      && docker push $DOCKER_LOGIN/monolithic-shop:latest;"
  on:
    condition: "$BUILD_TARGET == './monolithic/ui'"
    all_branches: true
