language: java
jdk: oraclejdk8

install:
  - ./gradlew clean jar
script:
  - ./gradlew test
after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
before_deploy:
  - ./gradlew jacocoTestCoverageVerification
deploy:
  provider: script
  script:
    - echo 'WIP'
    - echo 'WIP2'
  on:
    all_branches: true
#    condition: $TRAVIS_BRANCH =~ ^master$
